"""
detector.py — AEGIS Detection Engine
Responsibility: Main orchestrator. Wires together evaluator functions,
applies priority logic, computes severity scores, and builds alert dicts.
Exposes: detect_all(normalized_logs) → List[Alert]
"""

import sys
from datetime import datetime, timezone

from rules import (
    RULES,
    PRIORITY_ORDER,
    SEVERITY_BASE,
    SEVERITY_REASON_BONUS,
)
from evaluator import RULE_EVALUATORS


# ──────────────────────────────────────────────
# RULE LEVEL SETS — pre-computed for O(1) lookup
# ──────────────────────────────────────────────

_ATTACK_RULE_IDS    = {r["id"] for r in RULES if r["level"] == "ATTACK"}
_HIGH_RISK_RULE_IDS = {r["id"] for r in RULES if r["level"] == "HIGH_RISK"}
_SUSPICIOUS_RULE_IDS = {r["id"] for r in RULES if r["level"] == "SUSPICIOUS"}
# INFO-level rules contribute reasons but do NOT affect alert level


# ══════════════════════════════════════════════
# STEP 1: EVALUATE ALL RULES AGAINST ONE LOG
# Returns a dict of { rule_id: reason_string } for every triggered rule.
# ══════════════════════════════════════════════

def apply_rules(log: dict) -> dict[str, str]:
    """
    Run every registered evaluator against the log.
    Collect all triggered rules (regardless of their level).
    Returns { rule_id: reason_text } for triggered rules only.

    Multi-reason accumulation:
      - All triggered rules are recorded — not just the highest-priority one.
      - This gives frontends all context for one alert.
      - Example: { "server_error": "HTTP=500", "extreme_latency": "4200ms" }
    """
    triggered = {}
    for rule_id, evaluator_fn in RULE_EVALUATORS.items():
        try:
            fired, reason = evaluator_fn(log)
            if fired and reason:
                triggered[rule_id] = reason  # dict ensures no duplicate rule IDs
        except Exception as e:
            print(
                f"[DETECTOR] WARN: Rule '{rule_id}' raised exception on log "
                f"'{log.get('log_id', '?')}' — {e}. Skipping rule.",
                file=sys.stderr,
            )
    return triggered


# ══════════════════════════════════════════════
# STEP 2: DETERMINE ALERT LEVEL (PRIORITY ORDER)
# ATTACK > HIGH_RISK > SUSPICIOUS > CLEAN
# ══════════════════════════════════════════════

def determine_level(triggered_rules: dict[str, str]) -> str:
    """
    Walk PRIORITY_ORDER top→bottom.
    Return the FIRST level that has at least one triggered rule.
    If nothing triggered → CLEAN.

    Priority enforcement:
      - Once ATTACK is found, we return immediately.
      - HIGH_RISK can only be the final level if NO ATTACK rules fired.
      - SUSPICIOUS only if neither ATTACK nor HIGH_RISK fired.
    """
    if any(rule_id in triggered_rules for rule_id in _ATTACK_RULE_IDS):
        return "ATTACK"
    if any(rule_id in triggered_rules for rule_id in _HIGH_RISK_RULE_IDS):
        return "HIGH_RISK"
    if any(rule_id in triggered_rules for rule_id in _SUSPICIOUS_RULE_IDS):
        return "SUSPICIOUS"
    return "CLEAN"


# ══════════════════════════════════════════════
# STEP 3: COMPUTE SEVERITY SCORE (0–100)
# Base score (level) + bonus per triggered rule.
# Capped at 100.
# ══════════════════════════════════════════════

def compute_severity(alert_level: str, triggered_rules: dict[str, str]) -> int:
    """
    Severity score gives a numeric signal for ranking/sorting alerts.

    Formula:
        base_score = SEVERITY_BASE[alert_level]
        bonus      = sum of SEVERITY_REASON_BONUS[rule_id] for each triggered rule
        score      = min(base_score + bonus, 100)

    Examples:
        ATTACK + server_error + invalid_hardware_id → 80 + 10 + 15 = 100 (capped)
        HIGH_RISK + extreme_latency → 50 + 8 = 58
        SUSPICIOUS + elevated_latency → 25 + 5 = 30
        CLEAN → 0
    """
    base = SEVERITY_BASE.get(alert_level, 0)
    bonus = sum(
        SEVERITY_REASON_BONUS.get(rule_id, 0)
        for rule_id in triggered_rules
    )
    return min(base + bonus, 100)


# ══════════════════════════════════════════════
# STEP 4: BUILD FINAL ALERT DICT
# ══════════════════════════════════════════════

def build_alert(log: dict, alert_level: str, triggered_rules: dict[str, str]) -> dict:
    """
    Assemble the final Alert dict from log data + detection results.

    Fields:
        log_id           → from normalized log (mandatory)
        node_id          → from normalized log (mandatory)
        node_name        → from node_registry (or "UNKNOWN")
        region           → from node_registry (or "UNKNOWN")
        timestamp        → log event time from Step 1 (or "UNKNOWN")
        ingestion_time   → UTC time this alert was generated by the engine
        alert_level      → ATTACK / HIGH_RISK / SUSPICIOUS / CLEAN
        severity_score   → 0–100 numeric rank (base + per-rule bonus)
        confidence_score → 0–100 percent certainty: more rules fired = higher
        is_anomaly       → True for any non-CLEAN alert
        primary_reason   → first (most important) reason string, or None
        reasons          → full list of triggered reason strings
        rule_ids         → triggered rule IDs (for programmatic filtering)
        source_data      → snapshot of raw values for dashboard columns
        parse_warnings   → soft errors forwarded from Step 1 normalization
    """
    reasons = list(triggered_rules.values())
    rule_ids = list(triggered_rules.keys())
    severity = compute_severity(alert_level, triggered_rules)

    # confidence_score: each fired rule adds ~25 points, capped at 100
    # 1 rule = 25%, 2 rules = 50%, 3 rules = 75%, 4+ rules = 100%
    confidence_score = min(len(triggered_rules) * 25, 100)

    # primary_reason: the first reason in the list (highest-priority rule fires first
    # because RULE_EVALUATORS dict maintains insertion order in Python 3.7+)
    primary_reason = reasons[0] if reasons else None

    # ingestion_time: when the detection engine processed this log (UTC)
    ingestion_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    return {
        "log_id":           log.get("log_id", "UNKNOWN"),
        "node_id":          log.get("node_id", "UNKNOWN"),
        "node_name":        log.get("node_name", "UNKNOWN"),
        "region":           log.get("region", "UNKNOWN"),
        "timestamp":        log.get("timestamp", "UNKNOWN"),
        "ingestion_time":   ingestion_time,
        "alert_level":      alert_level,
        "severity_score":   severity,
        "confidence_score": confidence_score,
        "is_anomaly":       alert_level != "CLEAN",
        "primary_reason":   primary_reason,
        "reasons":          reasons,
        "rule_ids":         rule_ids,
        "source_data": {
            "reported_status":    log.get("reported_status", "UNKNOWN"),
            "http_status":        log.get("http_status", -1),
            "response_time_ms":   log.get("response_time_ms", -1),
            "hardware_id_b64":    log.get("hardware_id_b64"),
            "hardware_id_valid":  log.get("hardware_id_valid", False),
            "hardware_id_decoded": log.get("hardware_id_decoded"),
            "schema_version":     log.get("schema_version", -1),
            "schema_known":       log.get("schema_known", False),
        },
        "parse_warnings": log.get("parse_warnings", []),
    }


# ══════════════════════════════════════════════
# MAIN ENTRY POINT: evaluate one log
# ══════════════════════════════════════════════

def evaluate_log(log: dict) -> dict | None:
    """
    Full evaluation of a single normalized log.
    Returns an Alert dict, or None if the log cannot be processed.

    Steps:
        1. Guard: must have log_id and node_id
        2. apply_rules()      → collect all triggered rules
        3. determine_level()  → ATTACK / HIGH_RISK / SUSPICIOUS / CLEAN
        4. build_alert()      → assemble output dict
    """
    # ── Guard: minimum viable log ─────────────────────────────────────────
    if not isinstance(log, dict):
        print("[DETECTOR] ERROR: log is not a dict — skipping", file=sys.stderr)
        return None

    log_id = str(log.get("log_id") or "").strip()
    node_id = str(log.get("node_id") or "").strip()
    if not log_id or not node_id:
        print(
            f"[DETECTOR] ERROR: log missing log_id or node_id — skipping: {log}",
            file=sys.stderr,
        )
        return None

    # ── Core pipeline ─────────────────────────────────────────────────────
    triggered = apply_rules(log)
    level = determine_level(triggered)
    alert = build_alert(log, level, triggered)
    return alert


# ══════════════════════════════════════════════
# BATCH ENTRY POINT: evaluate full list
# ══════════════════════════════════════════════

def detect_all(normalized_logs: list[dict]) -> tuple[list[dict], dict]:
    """
    Run detection engine on every normalized log (single pass, O(n)).

    Returns:
        alerts  → List[Alert] — one entry per log (including CLEAN)
        summary → aggregate stats dict for API /metrics endpoint

    Summary fields:
        total, attack_count, high_risk_count, suspicious_count, clean_count,
        avg_response_time_ms, invalid_hw_count, nodes_under_attack,
        schema_versions_seen
    """
    alerts = []
    skipped = 0

    # Aggregation accumulators
    counts = {"ATTACK": 0, "HIGH_RISK": 0, "SUSPICIOUS": 0, "CLEAN": 0}
    latencies = []
    invalid_hw = 0
    attacked_nodes = set()
    schema_versions_seen = set()

    for raw_log in normalized_logs:
        try:
            alert = evaluate_log(raw_log)
            if alert is None:
                skipped += 1
                continue

            alerts.append(alert)

            # Aggregate
            level = alert["alert_level"]
            counts[level] = counts.get(level, 0) + 1

            rt = alert["source_data"].get("response_time_ms", -1)
            if rt != -1:
                latencies.append(rt)

            if not alert["source_data"].get("hardware_id_valid", True):
                invalid_hw += 1

            if level == "ATTACK":
                attacked_nodes.add(alert["node_id"])

            sv = alert["source_data"].get("schema_version", -1)
            if sv != -1:
                schema_versions_seen.add(sv)

        except Exception as e:
            log_id = raw_log.get("log_id", "?") if isinstance(raw_log, dict) else "?"
            print(
                f"[DETECTOR] CRITICAL: Unexpected error on log '{log_id}' — {e}. Skipping.",
                file=sys.stderr,
            )
            skipped += 1

    avg_latency = round(sum(latencies) / len(latencies), 1) if latencies else 0.0

    summary = {
        "total_logs_processed": len(alerts) + skipped,
        "total_alerts":         len(alerts),
        "skipped":              skipped,
        "attack_count":         counts["ATTACK"],
        "high_risk_count":      counts["HIGH_RISK"],
        "suspicious_count":     counts["SUSPICIOUS"],
        "clean_count":          counts["CLEAN"],
        "avg_response_time_ms": avg_latency,
        "invalid_hw_count":     invalid_hw,
        "nodes_under_attack":   sorted(attacked_nodes),
        "schema_versions_seen": sorted(schema_versions_seen),
    }

    print(
        f"[DETECTOR] Done: total={len(alerts)}, ATTACK={counts['ATTACK']}, "
        f"HIGH_RISK={counts['HIGH_RISK']}, SUSPICIOUS={counts['SUSPICIOUS']}, "
        f"CLEAN={counts['CLEAN']}, skipped={skipped}"
    )
    return alerts, summary
